# -*- coding: utf-8 -*-
"""
Schemas模块

本模块包含所有Pydantic数据模型定义。
"""

from app.schemas.document import (
    DocumentBase,
    DocumentCreate,
    DocumentUpdate,
    DocumentListItem,
    DocumentDetailResponse,
    VersionListItem,
    VersionDetailResponse,
    UploadResult,
    FailedFile,
    BatchUploadResponse,
    ImportTaskResponse,
    ImportTaskListItem,
)
from app.schemas.cleaning import (
    CleaningRuleBase,
    CleaningRuleCreate,
    CleaningRuleUpdate,
    CleaningRuleResponse,
    CleaningLogResponse,
    CleanedElement,
    CleaningResult,
    CleaningConfig,
    BatchCleaningRequest,
)
from app.schemas.chunk import (
    ChunkConfigRequest,
    ChunkElement,
    ChunkingResult,
    ChunkStatistics,
    ChunkListItem,
    ChunkDetailResponse,
    BatchChunkingRequest,
    BatchChunkingResponse,
)
from app.schemas.embedding import (
    EmbeddingConfigRequest,
    EmbeddingRequest,
    EmbeddingResponse,
    SingleEmbeddingRequest,
    SingleEmbeddingResponse,
    ChunkEmbeddingRequest,
    ChunkEmbeddingResult,
    ChunkEmbeddingResponse,
    VectorSearchRequest,
    VectorSearchResult,
    VectorSearchResponse,
    VectorStatistics,
    VectorDeleteRequest,
    VectorDeleteResponse,
)
from app.schemas.keyword import (
    KeywordIndexRequest,
    KeywordIndexResult,
    KeywordIndexResponse,
    KeywordSearchRequest,
    KeywordSearchResult,
    KeywordSearchResponse,
    IndexStatistics,
)
from app.schemas.retrieval import (
    RetrievalRequest,
    RetrievalResponse,
    RetrievalResult,
    ChunkReference,
    VectorSearchRequest as RetrievalVectorSearchRequest,
    KeywordSearchRequest as RetrievalKeywordSearchRequest,
    SuggestionResponse,
    FusionRequest,
    QueryRewriteRequest,
    QueryRewriteResponse,
    RetrievalStatistics,
)
from app.schemas.queue import (
    TaskType,
    TaskStatus,
    QueueName,
    RoutingKey,
    TaskMessage,
    ParseTaskMessage,
    CleanTaskMessage,
    ChunkTaskMessage,
    EmbeddingTaskMessage,
    IndexTaskMessage,
    TaskResult,
    DeadLetterMessage,
    QueueStats,
    WorkerConfig,
)

__all__ = [
    # 文档相关
    "DocumentBase",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentListItem",
    "DocumentDetailResponse",
    "VersionListItem",
    "VersionDetailResponse",
    "UploadResult",
    "FailedFile",
    "BatchUploadResponse",
    "ImportTaskResponse",
    "ImportTaskListItem",
    # 清洗相关
    "CleaningRuleBase",
    "CleaningRuleCreate",
    "CleaningRuleUpdate",
    "CleaningRuleResponse",
    "CleaningLogResponse",
    "CleanedElement",
    "CleaningResult",
    "CleaningConfig",
    "BatchCleaningRequest",
    # 切分相关
    "ChunkConfigRequest",
    "ChunkElement",
    "ChunkingResult",
    "ChunkStatistics",
    "ChunkListItem",
    "ChunkDetailResponse",
    "BatchChunkingRequest",
    "BatchChunkingResponse",
    # 向量化相关
    "EmbeddingConfigRequest",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "SingleEmbeddingRequest",
    "SingleEmbeddingResponse",
    "ChunkEmbeddingRequest",
    "ChunkEmbeddingResult",
    "ChunkEmbeddingResponse",
    "VectorSearchRequest",
    "VectorSearchResult",
    "VectorSearchResponse",
    "VectorStatistics",
    "VectorDeleteRequest",
    "VectorDeleteResponse",
    # 关键词相关
    "KeywordIndexRequest",
    "KeywordIndexResult",
    "KeywordIndexResponse",
    "KeywordSearchRequest",
    "KeywordSearchResult",
    "KeywordSearchResponse",
    "IndexStatistics",
    # 检索相关
    "RetrievalRequest",
    "RetrievalResponse",
    "RetrievalResult",
    "ChunkReference",
    "RetrievalVectorSearchRequest",
    "RetrievalKeywordSearchRequest",
    "SuggestionResponse",
    "FusionRequest",
    "QueryRewriteRequest",
    "QueryRewriteResponse",
    "RetrievalStatistics",
    # 队列相关
    "TaskType",
    "TaskStatus",
    "QueueName",
    "RoutingKey",
    "TaskMessage",
    "ParseTaskMessage",
    "CleanTaskMessage",
    "ChunkTaskMessage",
    "EmbeddingTaskMessage",
    "IndexTaskMessage",
    "TaskResult",
    "DeadLetterMessage",
    "QueueStats",
    "WorkerConfig",
]
